CANCEL = '↩️Назад'
MAIN_MENU_USERS = '🎭Пользователи'
MAIN_MENU_ACCOUNTS = '😺Аккаунт'
MAIN_MENU_CHATS = '📋Чаты'
MAIN_MENU_FAQ = '❓FAQ'
ADD_CHAT = '❇️Добавить чат'
DEL_CHAT = '❌Удалить чат'
FIND_CHAT = '🔍Поиск чата'
COPY_MESSAGES = '📑Копировать сообщения'
LIST_CHATS = '📋Список чатов'
YES = '✅Да'
NO = '❌Нет'
COUNT_CHATS_WIDTH = 1
COUNT_CHATS_HEIGHT = 10
COUNT_MESSAGES_WIDTH = 1
COUNT_MESSAGES_HEIGHT = 10
COUNT_USERS_WIDTH = 1
COUNT_USERS_HEIGHT = 10
ADD_MESSAGE = '❇️Добавить сообщение'
FIND_MESSAGE = '🔍Поиск сообщения'
CHANGE_CHAT_NAME = '✏️Изменить название чата'
CHAT_MESSAGES = '📋Список сообщений'
CHANGE_MESSAGE_NAME = '✏️Изменить название'
CHANGE_MESSAGE_TEXT = '📝Изменить текст'
CHANGE_MESSAGE_DATETIME = '🕒Изменить дату и время отправки'
DEL_MESSAGE = '❌Удалить сообщение'
WITHOUT_DATETIME = 'Без времени'
DOWNLOAD_MESSAGES_FROM_EXCEL = '📥Загрузить сообщения из Excel'
ADD_USER = '❇️Добавить пользователя'
DEL_USERS = '❌Удалить'
LIST_USERS = '📋Список пользователей'
CHANGE_ROLE_USERS = '✏️Изменить роль'
CREATE_USER_LINK_YES = '✅Сформировать'
CREATE_USER_LINK_NO = '❌Отмена'
