CANCEL = "↩️Назад"
MAIN_MENU_USERS = "Пользователи"
MAIN_MENU_ACCOUNTS = "Аккаунт"
MAIN_MENU_CHATS = "Чаты"
MAIN_MENU_FAQ = "FAQ"
ADD_CHAT = "Добавить чат"
DEL_CHAT = "Удалить чат"
FIND_CHAT = "Поиск чата"
COPY_MESSAGES = "Копировать сообщения"
YES = "Да"
NO = "Нет"
COUNT_CHATS_WIDTH = 1
COUNT_CHATS_HEIGHT = 5
